name: weather
description: A Weather app Project created.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  dio: ^4.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  intl: ^0.17.0
  lottie: ^1.2.1
  network:
    path: packages/network
  pull_to_refresh: ^2.0.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated/
  lineLength: 80

  integrations:
    flutter_svg: true
